<?php

namespace Admin\MedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * activiadrolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadrolRepository extends EntityRepository
{
    public function decarrera(){
     $em = $this->getEntityManager(); 
    // $centros = $em->getRepository('AdminUnadBundle:Centro')->findAll();
     $query = $em->createQuery('SELECT a FROM AdminMedBundle:Actividadrol a WHERE a.id < 500 ORDER BY a.rol, a.id ASC');
     $actividades = $query->getResult(); 
     return $actividades;        
  }
    
}
