<?php

namespace Admin\MedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanmejoramientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanmejoramientoRepository extends EntityRepository
{
}
