<?php

namespace Admin\MedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoiRepository extends EntityRepository
{
 public function findByUser($user){
    $em = $this->getEntityManager();

    $query = $em->createQuery(
       'SELECT p.id, p.nombre
        FROM Admin\MedBundle\Entity\Proyectoi p
        WHERE p.user = :user'
    )->setParameter('user', $user);
    // returns an array of Product objects
    return $query->execute();
}  


 public function porUsuario($user){
  return $this->createQueryBuilder('proyectos_inv')
            ->where('proyectos_inv.user = :user')
            ->setParameter('user', $user)
            ->orderBy('proyectos_inv.nombre', 'ASC');
 }

public function findByUsuario($user)
{
    $conn = $this->getEntityManager()->getConnection();

    $sql = '
        SELECT p.id, p.nombre FROM proyectos_inv p
        WHERE p.user_id = '.$user.'
        ';
    $stmt = $conn->prepare($sql);
    
    $stmt->execute();

    // returns an array of arrays (i.e. a raw data set)
    return $stmt->fetchAll();
}

}
