<?php

namespace Admin\UnadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteRepository extends EntityRepository
{
     public function docentesPeriodo($periodo) {
    $connection = $this->getEntityManager()->getConnection();
    $q = "select doc.* from (select @periodoe_id:=".$periodo." p) param, docentes_periodo doc";
    $stmt = $connection->executeQuery($q);
    return $stmt->fetchAll();
}   
}
