<?php

namespace Admin\UnadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaRepository extends EntityRepository
{
    public function ordenEscuela(){
     $em = $this->getEntityManager(); 
    // $centros = $em->getRepository('AdminUnadBundle:Centro')->findAll();
     $query = $em->createQuery('SELECT a FROM AdminUnadBundle:Programa a ORDER BY a.escuela ASC');
     $centros = $query->getResult(); 
     return $centros;        
  }
  
      public function getPorEscuela($escuelaId){
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT a FROM AdminUnadBundle:Programa a WHERE a.escuela = :escuelaid')->setParameter('escuelaid', $escuelaId);    
        $programas = $query->getResult(); 
        return $programas;   
      }
  
  
}
