<?php

namespace Admin\UnadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramaPeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaPeriodoRepository extends EntityRepository
{
}
